In [2]:
import pandas as pd
import numpy as np

In [5]:
house_df=pd.read_csv("/Users/amelchristy/Desktop/Python_Project/Real_Estate_Lehigh 2/zip_code_market_tracker.tsv000 (1)",delimiter='\t')

In [6]:
house_df.head()

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,...,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2018-12-01,2019-02-28,90,zip code,2,24614,f,Zip Code: 57106,NaN,South Dakota,...,-0.041788,NaN,NaN,NaN,0.000000,0.000000,-0.130435,"Sioux Falls, SD",43620,2023-11-26 14:23:37
1,2016-04-01,2016-06-30,90,zip code,2,5033,f,Zip Code: 14086,NaN,New York,...,0.026709,NaN,NaN,NaN,0.115385,-0.075092,-0.145485,"Buffalo, NY",15380,2023-11-26 14:23:37
2,2019-10-01,2019-12-31,90,zip code,2,17977,f,Zip Code: 43044,NaN,Ohio,...,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,"Urbana, OH",46500,2023-11-26 14:23:37
3,2022-06-01,2022-08-31,90,zip code,2,16419,f,Zip Code: 38611,NaN,Mississippi,...,0.081063,NaN,NaN,NaN,0.588235,0.280543,0.588235,"Memphis, TN",32820,2023-11-26 14:23:37
4,2019-09-01,2019-11-30,90,zip code,2,20397,f,Zip Code: 48034,NaN,Michigan,...,-0.118182,NaN,NaN,NaN,0.000000,0.000000,-0.333333,"Warren, MI",47664,2023-11-26 14:23:37

In [5]:
house_df.keys()

Index(['period_begin', 'period_end', 'period_duration', 'region_type',
       'region_type_id', 'table_id', 'is_seasonally_adjusted', 'region',
       'city', 'state', 'state_code', 'property_type', 'property_type_id',
       'median_sale_price', 'median_sale_price_mom', 'median_sale_price_yoy',
       'median_list_price', 'median_list_price_mom', 'median_list_price_yoy',
       'median_ppsf', 'median_ppsf_mom', 'median_ppsf_yoy', 'median_list_ppsf',
       'median_list_ppsf_mom', 'median_list_ppsf_yoy', 'homes_sold',
       'homes_sold_mom', 'homes_sold_yoy', 'pending_sales',
       'pending_sales_mom', 'pending_sales_yoy', 'new_listings',
       'new_listings_mom', 'new_listings_yoy', 'inventory', 'inventory_mom',
       'inventory_yoy', 'months_of_supply', 'months_of_supply_mom',
       'months_of_supply_yoy', 'median_dom', 'median_dom_mom',
       'median_dom_yoy', 'avg_sale_to_list', 'avg_sale_to_list_mom',
       'avg_sale_to_list_yoy', 'sold_above_list', 'sold_above_list_mom',
       'sold_above_list_yoy', 'price_drops', 'price_drops_mom',
       'price_drops_yoy', 'off_market_in_two_weeks',
       'off_market_in_two_weeks_mom', 'off_market_in_two_weeks_yoy',
       'parent_metro_region', 'parent_metro_region_metro_code',
       'last_updated'],
      dtype='object')

In [7]:
house_df.shape

(7561517, 58)

In [8]:
pd.set_option('display.max_columns', 58)

# Show the first 5 rows of the DataFrame with all columns
print(house_df.tail())

        period_begin  period_end  period_duration region_type  region_type_id  \
7561512   2020-12-01  2021-02-28               90    zip code               2
7561513   2017-05-01  2017-07-31               90    zip code               2
7561514   2017-01-01  2017-03-31               90    zip code               2
7561515   2020-02-01  2020-04-30               90    zip code               2
7561516   2015-12-01  2016-02-29               90    zip code               2

         table_id is_seasonally_adjusted           region  city  \
7561512      1053                      f  Zip Code: 03235   NaN
7561513       393                      f  Zip Code: 01515   NaN
7561514      7605                      f  Zip Code: 19522   NaN
7561515      7202                      f  Zip Code: 18762   NaN
7561516     26839                      f  Zip Code: 62240   NaN

                 state state_code              property_type  \
7561512  New Hampshire         NH                Condo/Co-op
7561513  Massachusetts         MA            All Residential
7561514   Pennsylvania         PA                  Townhouse
7561515   Pennsylvania         PA            All Residential
7561516       Illinois         IL  Single Family Residential

         property_type_id  median_sale_price  median_sale_price_mom  \
7561512                 3           154900.0                    NaN
7561513                -1           249900.0              -0.000400
7561514                13           123000.0               0.000000
7561515                -1            60000.0               0.000000
7561516                 6            76750.0               0.300847

         median_sale_price_yoy  median_list_price  median_list_price_mom  \
7561512                    NaN           155000.0                    NaN
7561513               0.125676           244900.0               0.065941
7561514               0.128440           119900.0               0.000000
7561515                    NaN                NaN                    NaN
7561516               6.309524            37000.0              -0.382819

         median_list_price_yoy  median_ppsf  median_ppsf_mom  median_ppsf_yoy  \
7561512                    NaN    58.109210              NaN              NaN
7561513              -0.039231   174.818841        -0.015026         0.191358
7561514               0.000000    85.416667         0.000000         0.200320
7561515                    NaN    32.258065         0.000000              NaN
7561516               1.960000    39.849320         0.197639         4.271938

         median_list_ppsf  median_list_ppsf_mom  median_list_ppsf_yoy  \
7561512         93.093093                   NaN                   NaN
7561513        145.781250             -0.100299             -0.084764
7561514         88.315789              0.024471             -0.015194
7561515               NaN                   NaN                   NaN
7561516         24.666667             -0.187396              1.870303

         homes_sold  homes_sold_mom  homes_sold_yoy  pending_sales  \
7561512         2.0             NaN             NaN            NaN
7561513         9.0             0.0       -0.181818            2.0
7561514         3.0            -0.4        0.500000            3.0
7561515         1.0             0.0             NaN            NaN
7561516         6.0             2.0        0.500000            NaN

         pending_sales_mom  pending_sales_yoy  new_listings  new_listings_mom  \
7561512                NaN                NaN           1.0               NaN
7561513                NaN          -0.666667          11.0              0.10
7561514                NaN           0.500000          11.0              1.75
7561515                NaN                NaN           NaN               NaN
7561516                NaN                NaN           3.0             -0.25

         new_listings_yoy  inventory  inventory_mom  inventory_yoy  \
7561512               NaN        1.0            NaN            NaN
7561513             -0.45       16.0       0.066667      -0.238095
7561514              1.20       11.0       0.571429       1.200000
7561515               NaN        1.0       0.000000            NaN
7561516              0.00        4.0      -0.555556       3.000000

         months_of_supply  months_of_supply_mom  months_of_supply_yoy  \
7561512               NaN                   NaN                   NaN
7561513               NaN                   NaN                   NaN
7561514               NaN                   NaN                   NaN
7561515               NaN                   NaN                   NaN
7561516               NaN                   NaN                   NaN

         median_dom  median_dom_mom  median_dom_yoy  avg_sale_to_list  \
7561512       208.5             NaN             NaN          1.000000
7561513        22.0             0.0            14.0          1.000122
7561514        80.0            27.0          -101.5          0.982294
7561515       170.0             0.0             NaN          0.869565
7561516        90.5            21.0            30.5          0.910841

         avg_sale_to_list_mom  avg_sale_to_list_yoy  sold_above_list  \
7561512                   NaN                   NaN         0.000000
7561513              0.001026              0.018122         0.333333
7561514              0.024638              0.100721         0.000000
7561515              0.000000                   NaN         0.000000
7561516              0.021836              0.057271         0.000000

         sold_above_list_mom  sold_above_list_yoy  price_drops  \
7561512                  NaN                  NaN          NaN
7561513                  0.0             0.151515          NaN
7561514                  0.0             0.000000          NaN
7561515                  0.0                  NaN          NaN
7561516                  0.0             0.000000          NaN

         price_drops_mom  price_drops_yoy  off_market_in_two_weeks  \
7561512              NaN              NaN                      NaN
7561513              NaN              NaN                 0.500000
7561514              NaN              NaN                 0.666667
7561515              NaN              NaN                      NaN
7561516              NaN              NaN                 0.000000

         off_market_in_two_weeks_mom  off_market_in_two_weeks_yoy  \
7561512                          NaN                          NaN
7561513                          NaN                     0.333333
7561514                          NaN                     0.166667
7561515                          NaN                          NaN
7561516                          NaN                     0.000000

        parent_metro_region  parent_metro_region_metro_code  \
7561512         Concord, NH                           18180
7561513       Worcester, MA                           49340
7561514         Reading, PA                           39740
7561515        Scranton, PA                           42540
7561516       St. Louis, MO                           41180

                last_updated
7561512  2023-11-26 14:23:37
7561513  2023-11-26 14:23:37
7561514  2023-11-26 14:23:37
7561515  2023-11-26 14:23:37
7561516  2023-11-26 14:23:37

In [9]:
#remove zipcode string under region column 
house_df['zipcode'] = house_df['region'].str.replace(r'Zip Code: ', '', regex=True)


# Display the DataFrame to verify the column is cleaned
house_df

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,...,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated,zipcode
0,2018-12-01,2019-02-28,90,zip code,2,24614,f,Zip Code: 57106,NaN,South Dakota,SD,All Residential,-1,213500.0,0.010651,0.047853,219700.0,0.028077,0.051699,117.252931,0.001910,0.057700,118.767145,0.006820,0.027307,111.0,-0.207143,-0.146154,19.0,...,-0.173913,122.0,0.109091,-0.134752,162.0,0.087248,-0.012195,NaN,NaN,NaN,81.0,14.0,11.0,0.979745,-0.004461,-0.010227,0.135135,-0.007722,-0.041788,NaN,NaN,NaN,0.000000,0.000000,-0.130435,"Sioux Falls, SD",43620,2023-11-26 14:23:37,57106
1,2016-04-01,2016-06-30,90,zip code,2,5033,f,Zip Code: 14086,NaN,New York,NY,Single Family Residential,6,199350.0,0.038281,0.092628,249900.0,0.135909,0.075301,116.488459,0.078156,0.029912,120.108745,-0.004497,0.008726,78.0,0.238095,0.083333,26.0,...,-0.434783,116.0,0.017544,-0.256410,97.0,0.141176,-0.344595,NaN,NaN,NaN,54.0,-18.0,-61.5,0.983976,0.011231,-0.004981,0.346154,0.092186,0.026709,NaN,NaN,NaN,0.115385,-0.075092,-0.145485,"Buffalo, NY",15380,2023-11-26 14:23:37,14086
2,2019-10-01,2019-12-31,90,zip code,2,17977,f,Zip Code: 43044,NaN,Ohio,OH,Single Family Residential,6,183887.0,0.152897,0.339796,154900.0,0.000000,0.240192,85.034221,0.126302,-0.079074,94.455316,0.000000,-0.044860,10.0,0.111111,0.000000,5.0,...,4.000000,11.0,0.000000,0.100000,6.0,-0.571429,-0.647059,NaN,NaN,NaN,66.0,-7.0,-2.5,0.990772,0.020588,0.003037,0.200000,-0.022222,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,"Urbana, OH",46500,2023-11-26 14:23:37,43044
3,2022-06-01,2022-08-31,90,zip code,2,16419,f,Zip Code: 38611,NaN,Mississippi,MS,All Residential,-1,340000.0,0.000000,0.357285,349250.0,-0.168254,0.042693,157.297576,-0.006996,0.248393,162.105758,-0.007313,0.176632,43.0,-0.044444,0.228571,17.0,...,0.700000,50.0,-0.074074,0.562500,28.0,0.037037,-0.282051,NaN,NaN,NaN,6.5,1.0,-52.5,1.003796,0.003849,0.012217,0.395349,-0.093540,0.081063,NaN,NaN,NaN,0.588235,0.280543,0.588235,"Memphis, TN",32820,2023-11-26 14:23:37,38611
4,2019-09-01,2019-11-30,90,zip code,2,20397,f,Zip Code: 48034,NaN,Michigan,MI,Single Family Residential,6,231650.0,-0.034389,-0.172679,299900.0,-0.000167,0.100752,94.444444,-0.029666,-0.089638,119.750000,0.024105,0.223819,11.0,-0.153846,0.100000,2.0,...,-0.333333,13.0,0.083333,0.083333,9.0,0.500000,-0.100000,NaN,NaN,NaN,28.0,4.0,10.0,0.953366,-0.011263,-0.045505,0.181818,0.027972,-0.118182,NaN,NaN,NaN,0.000000,0.000000,-0.333333,"Warren, MI",47664,2023-11-26 14:23:37,48034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7561512,2020-12-01,2021-02-28,90,zip code,2,1053,f,Zip Code: 03235,NaN,New Hampshire,NH,Condo/Co-op,3,154900.0,NaN,NaN,155000.0,NaN,NaN,58.109210,NaN,NaN,93.093093,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,208.5,NaN,NaN,1.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Concord, NH",18180,2023-11-26 14:23:37,03235
7561513,2017-05-01,2017-07-31,90,zip code,2,393,f,Zip Code: 01515,NaN,Massachusetts,MA,All Residential,-1,249900.0,-0.000400,0.125676,244900.0,0.065941,-0.039231,174.818841,-0.015026,0.191358,145.781250,-0.100299,-0.084764,9.0,0.000000,-0.181818,2.0,...,-0.666667,11.0,0.100000,-0.450000,16.0,0.066667,-0.238095,NaN,NaN,NaN,22.0,0.0,14.0,1.000122,0.001026,0.018122,0.333333,0.000000,0.151515,NaN,NaN,NaN,0.500000,NaN,0.333333,"Worcester, MA",49340,2023-11-26 14:23:37,01515
7561514,2017-01-01,2017-03-31,90,zip code,2,7605,f,Zip Code: 19522,NaN,Pennsylvania,PA,Townhouse,13,123000.0,0.000000,0.128440,119900.0,0.000000,0.000000,85.416667,0.000000,0.200320,88.315789,0.024471,-0.015194,3.0,-0.400000,0.500000,3.0,...,0.500000,11.0,1.750000,1.200000,11.0,0.571429,1.200000,NaN,NaN,NaN,80.0,27.0,-101.5,0.982294,0.024638,0.100721,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.666667,NaN,0.166667,"Reading, PA",39740,2023-11-26 14:23:37,19522
7561515,2020-02-01,2020-04-30,90,zip code,2,7202,f,Zip Code: 18762,NaN,Pennsylvania,PA,All Residential,-1,60000.0,0.000000,NaN,NaN,NaN,NaN,32.258065,0.000000,NaN,NaN,NaN,NaN,1.0,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,0.000000,NaN,NaN,NaN,NaN,170.0,0.0,NaN,0.869565,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Scranton, PA",42540,2023-11-26 14:23:37,18762
7561516,2015-12-01,2016-02-29,90,zip code,2,26839,f,Zip Code: 62240,NaN,Illinois,IL,Single Family Residential,6,76750.0,0.300847,6.309524,37000.0,-0.382819,1.960000,39.849320,0.197639,4.271938,24.666667,-0.187396,1.870303,6.0,2.000000,0.500000,NaN,...,NaN,3.0,-0.250000,0.000000,4.0,-0.555556,3.000000,NaN,NaN,NaN,90.5,21.0,30.5,0.910841,0.021836,0.057271,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,0.000000,"St. Louis, MO",41180,2023-11-26 14:23:37,62240

In [15]:
house_df.keys()

Index(['period_begin', 'period_end', 'period_duration', 'region_type',
       'region_type_id', 'table_id', 'is_seasonally_adjusted', 'region',
       'city', 'state', 'state_code', 'property_type', 'property_type_id',
       'median_sale_price', 'median_sale_price_mom', 'median_sale_price_yoy',
       'median_list_price', 'median_list_price_mom', 'median_list_price_yoy',
       'median_ppsf', 'median_ppsf_mom', 'median_ppsf_yoy', 'median_list_ppsf',
       'median_list_ppsf_mom', 'median_list_ppsf_yoy', 'homes_sold',
       'homes_sold_mom', 'homes_sold_yoy', 'pending_sales',
       'pending_sales_mom', 'pending_sales_yoy', 'new_listings',
       'new_listings_mom', 'new_listings_yoy', 'inventory', 'inventory_mom',
       'inventory_yoy', 'months_of_supply', 'months_of_supply_mom',
       'months_of_supply_yoy', 'median_dom', 'median_dom_mom',
       'median_dom_yoy', 'avg_sale_to_list', 'avg_sale_to_list_mom',
       'avg_sale_to_list_yoy', 'sold_above_list', 'sold_above_list_mom',
       'sold_above_list_yoy', 'price_drops', 'price_drops_mom',
       'price_drops_yoy', 'off_market_in_two_weeks',
       'off_market_in_two_weeks_mom', 'off_market_in_two_weeks_yoy',
       'parent_metro_region', 'parent_metro_region_metro_code', 'last_updated',
       'zipcode'],
      dtype='object')

In [10]:
house_df['city']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
           ..
7561512   NaN
7561513   NaN
7561514   NaN
7561515   NaN
7561516   NaN
Name: city, Length: 7561517, dtype: float64

In [11]:
house_df = house_df.drop(columns=['city'])

In [13]:
#population_df = pd.read_csv("/Users/amelchristy/Desktop/Python_Project/Real_Estate_Lehighuscities_population_details.csv")#

In [14]:
#pip install xlrd

In [12]:
# read by default 1st sheet of an excel file
population_df = pd.read_excel("/Users/amelchristy/Desktop/Python_Project/Real_Estate_Lehigh/uscities_population_details.xlsx")

In [13]:
#remove the space on the zipcode 
population_df.head()

,city,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,lng,population,population_proper,density,source,military,incorporated,cdp,timezone,ranking,zips,id,age_median,male,female,married,family_size,income_household_median,income_household_six_figure,home_ownership,home_value,rent_median,education_college_or_above,labor_force_participation,unemployment_rate,race_white,race_black,race_asian,race_native,race_pacific,race_other,race_multiple
0,New York,NY,New York,36081,Queens,36081|36047|36085|36005|36061,Queens|Kings|Richmond|Bronx|New York,40.6943,-73.9249,18908608.0,8736047.0,11226.2,shape,False,True,False,America/New_York,1,11229 11228 11226 11225 11224 11222 11221 1122...,1840034016,37.3,48.0,52.0,39.9,3.41,70663.0,36.9,33.2,659738.0,1579.0,39.6,63.4,7.5,39.8,23.4,14.2,0.5,0.1,14.9,7.1
1,Los Angeles,CA,California,6037,Los Angeles,6037,Los Angeles,34.1141,-118.4068,11922389.0,3902440.0,3202.3,shape,False,True,False,America/Los_Angeles,1,91367 90291 90293 90292 91316 91311 90035 9003...,1840020491,36.2,49.8,50.2,38.9,3.55,69778.0,35.6,36.9,705680.0,1641.0,36.2,66.7,7.6,44.9,8.6,11.7,0.9,0.2,24.0,9.8
2,Chicago,IL,Illinois,17031,Cook,17031|17043,Cook|DuPage,41.8375,-87.6866,8497759.0,2742119.0,4648.7,shape,False,True,False,America/Chicago,1,60018 60649 60641 60640 60643 60642 60645 6064...,1840000494,35.1,48.8,51.2,35.5,3.36,65781.0,33.3,45.6,277714.0,1209.0,41.7,67.3,8.4,45.3,29.2,6.8,0.5,0.0,10.7,7.4
3,Miami,FL,Florida,12086,Miami-Dade,12086,Miami-Dade,25.7840,-80.2101,6080145.0,440807.0,4728.2,shape,False,True,False,America/New_York,1,33128 33129 33125 33126 33127 33149 33144 3314...,1840015149,39.9,50.4,49.6,37.3,3.17,47860.0,23.1,30.0,368439.0,1361.0,33.0,64.6,5.6,55.0,15.2,1.4,0.3,0.0,5.2,22.9
4,Houston,TX,Texas,48201,Harris,48201|48157|48339,Harris|Fort Bend|Montgomery,29.7860,-95.3885,5970127.0,2293288.0,1382.2,shape,False,True,False,America/Chicago,1,77069 77068 77061 77060 77063 77062 77065 7706...,1840020925,33.7,49.8,50.2,41.2,3.36,56019.0,27.0,42.5,205913.0,1136.0,34.8,66.9,6.5,46.8,22.6,6.8,0.5,0.1,12.5,10.8

In [14]:
# split the zip 
pop_df= population_df.assign(zips=population_df['zips'].str.split()).explode('zips')

pop_df.reset_index(drop=True, inplace=True)


pop_df.shape

(131470, 40)

In [15]:
pop_df.head()

,city,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,lng,population,population_proper,density,source,military,incorporated,cdp,timezone,ranking,zips,id,age_median,male,female,married,family_size,income_household_median,income_household_six_figure,home_ownership,home_value,rent_median,education_college_or_above,labor_force_participation,unemployment_rate,race_white,race_black,race_asian,race_native,race_pacific,race_other,race_multiple
0,New York,NY,New York,36081,Queens,36081|36047|36085|36005|36061,Queens|Kings|Richmond|Bronx|New York,40.6943,-73.9249,18908608.0,8736047.0,11226.2,shape,False,True,False,America/New_York,1,11229,1840034016,37.3,48.0,52.0,39.9,3.41,70663.0,36.9,33.2,659738.0,1579.0,39.6,63.4,7.5,39.8,23.4,14.2,0.5,0.1,14.9,7.1
1,New York,NY,New York,36081,Queens,36081|36047|36085|36005|36061,Queens|Kings|Richmond|Bronx|New York,40.6943,-73.9249,18908608.0,8736047.0,11226.2,shape,False,True,False,America/New_York,1,11228,1840034016,37.3,48.0,52.0,39.9,3.41,70663.0,36.9,33.2,659738.0,1579.0,39.6,63.4,7.5,39.8,23.4,14.2,0.5,0.1,14.9,7.1
2,New York,NY,New York,36081,Queens,36081|36047|36085|36005|36061,Queens|Kings|Richmond|Bronx|New York,40.6943,-73.9249,18908608.0,8736047.0,11226.2,shape,False,True,False,America/New_York,1,11226,1840034016,37.3,48.0,52.0,39.9,3.41,70663.0,36.9,33.2,659738.0,1579.0,39.6,63.4,7.5,39.8,23.4,14.2,0.5,0.1,14.9,7.1
3,New York,NY,New York,36081,Queens,36081|36047|36085|36005|36061,Queens|Kings|Richmond|Bronx|New York,40.6943,-73.9249,18908608.0,8736047.0,11226.2,shape,False,True,False,America/New_York,1,11225,1840034016,37.3,48.0,52.0,39.9,3.41,70663.0,36.9,33.2,659738.0,1579.0,39.6,63.4,7.5,39.8,23.4,14.2,0.5,0.1,14.9,7.1
4,New York,NY,New York,36081,Queens,36081|36047|36085|36005|36061,Queens|Kings|Richmond|Bronx|New York,40.6943,-73.9249,18908608.0,8736047.0,11226.2,shape,False,True,False,America/New_York,1,11224,1840034016,37.3,48.0,52.0,39.9,3.41,70663.0,36.9,33.2,659738.0,1579.0,39.6,63.4,7.5,39.8,23.4,14.2,0.5,0.1,14.9,7.1

In [16]:
pop_df.keys()
pop_df_unique = pop_df.drop_duplicates(subset=['zips'])

pop_df_unique.shape

(22914, 40)

In [17]:
print(pop_df_unique.shape)
print(house_df.shape)

(22914, 40)
(7561517, 58)

In [18]:
# Convert the unique values in both columns to sets
unique_zips_population = set(pop_df_unique['zips'].unique())
unique_zips_house = set(house_df['zipcode'].unique())

# Find the intersection of both sets to see which zip codes are present in both dataframes
common_zips = unique_zips_population.intersection(unique_zips_house)

# Print out the common zip codes
print(common_zips)

# Check the length of the common zip codes set to see how many matches there are
print(f"Number of matching zip codes: {len(common_zips)}")

{'64119', '13418', '35968', '73012', '53217', '94548', '05468', '74464', '61236', '74108', '15442', '13417', '90290', '18936', '17022', '18211', '91115', '40906', '08027', '90059', '97068', '58703', '70079', '73090', '33765', '85353', '85202', '75203', '16045', '66101', '72437', '12538', '19526', '35951', '44705', '74339', '85392', '93001', '92024', '03079', '43721', '67901', '92336', '67110', '13810', '60567', '17763', '33137', '15926', '29646', '76116', '95383', '46807', '81649', '98148', '44672', '36609', '01518', '49945', '95817', '37043', '44805', '30710', '13212', '63135', '15004', '95822', '27573', '36303', '83440', '14428', '95420', '14420', '44889', '12288', '60480', '47385', '12068', '04073', '94103', '95333', '60611', '89706', '33613', '20024', '12089', '76384', '98228', '80919', '72928', '94565', '68403', '92027', '14031', '29464', '63115', '32765', '13616', '33617', '21037', '85901', '63132', '30238', '30016', '95571', '36605', '42003', '10468', '60041', '34481', '63039', '12561', '17520', '02341', '02128', '74456', '06057', '03225', '06255', '47040', '45226', '73013', '92626', '10595', '30338', '61323', '91935', '16502', '08628', '17611', '05669', '29649', '15421', '01970', '80003', '84096', '17532', '08107', '38046', '55438', '84091', '90093', '47885', '15037', '20705', '72072', '72376', '53718', '27217', '16420', '30563', '14174', '95421', '07034', '10524', '29687', '35046', '03802', '08807', '13862', '65619', '55079', '46327', '95368', '46360', '13615', '14105', '29405', '44221', '46283', '55415', '07946', '05070', '13734', '89170', '77369', '11729', '31705', '63031', '13319', '56340', '33142', '66206', '80921', '17329', '95976', '12929', '15760', '13034', '37830', '34953', '44264', '71758', '73116', '27832', '62684', '33851', '72176', '89145', '19087', '18512', '45002', '01259', '33162', '14893', '91016', '45015', '39564', '24184', '48503', '77382', '43408', '89103', '61605', '05448', '11358', '19333', '33035', '02043', '01432', '20901', '55129', '47374', '67223', '79536', '38028', '67505', '38182', '78741', '05470', '28127', '12927', '33603', '54729', '11361', '78121', '04274', '47162', '02804', '19530', '14423', '17777', '15484', '28375', '38506', '18960', '10537', '04021', '86406', '15765', '83443', '53537', '11435', '14821', '60623', '92106', '70550', '72018', '52658', '08343', '16041', '16803', '27253', '70750', '01524', '75165', '90278', '75758', '97123', '33860', '22066', '21108', '74061', '38025', '13478', '62220', '77090', '72117', '02664', '62526', '97367', '13409', '33583', '86441', '74114', '77043', '01801', '90221', '99329', '78574', '86334', '15468', '17065', '11096', '29732', '17090', '95372', '53151', '98390', '73079', '64034', '95130', '74119', '15531', '74871', '85234', '27809', '54901', '80007', '07746', '96062', '72370', '32548', '95959', '15237', '06070', '19014', '96821', '64134', '98293', '16052', '85752', '29605', '16878', '80134', '33316', '62712', '63147', '16845', '45764', '38133', '66211', '75401', '28428', '14738', '22901', '13633', '64841', '19720', '02713', '32773', '75224', '90046', '11370', '75569', '18618', '95776', '98363', '81004', '07870', '08501', '37853', '23606', '98113', '13654', '50674', '48093', '93662', '29630', '07927', '98007', '99504', '33487', '46237', '72717', '91741', '14839', '93031', '24550', '61279', '86005', '36022', '70130', '76227', '01243', '53177', '28395', '18350', '70570', '11969', '04332', '77034', '36785', '05201', '32137', '28690', '76133', '84746', '02842', '35094', '17976', '77083', '73142', '78146', '60608', '95387', '17853', '37714', '53960', '44485', '10034', '61068', '19474', '01227', '95367', '95065', '11003', '76522', '37312', '18846', '11242', '46350', '28698', '41102', '94974', '76132', '46012', '92131', '19718', '36203', '16872', '60942', '20118', '17102', '18951', '98421', '12592', '14094', '45404', '32757', '17042', '89110', '74082', '08875', '12729', '23177', '95986', '48557', '74865', '75208', '27530', '32872', '22801', '12885', '49405', '37011', '77017', '11414', '37037', '21770', '14625', '45233', '15429', '48197', '31632', '61360', '15465', '08518', '16504', '53532', '77471', '23062', '13082', '85225', '17324', '37085', '27357', '97405', '34211', '15044', '19610', '78583', '02887', '06109', '77586', '14742', '15655', '31403', '24211', '32911', '12019', '15635', '80138', '89136', '76185', '03740', '21783', '76547', '92661', '33843', '99577', '54482', '92507', '60651', '02852', '77263', '89107', '35057', '21114', '43738', '90007', '50317', '28679', '16030', '14425', '08750', '11427', '18086', '30607', '38703', '05407', '03780', '70390', '31771', '64057', '54614', '17730', '93117', '44848', '95926', '59808', '94954', '53963', '29483', '20894', '70559', '29486', '28212', '76708', '88354', '14141', '10504', '60604', '95037', '08081', '14125', '01560', '77551', '78207', '06110', '07601', '17350', '90291', '18840', '31525', '52404', '77702', '29455', '87532', '89033', '85379', '17506', '94806', '85743', '17507', '24411', '92307', '46903', '94042', '89503', '75501', '13776', '14424', '60097', '53187', '77396', '02452', '32937', '32316', '28814', '01342', '77055', '06853', '15957', '56387', '95602', '10601', '19067', '70058', '60601', '61821', '93060', '78853', '60476', '74104', '70715', '98144', '11021', '32305', '78701', '47523', '73085', '93620', '90026', '28792', '95677', '05261', '48640', '17923', '30108', '14513', '01230', '33029', '27862', '95826', '40513', '15936', '78751', '79901', '90247', '07510', '23188', '45202', '72223', '90607', '70810', '63101', '17862', '13054', '11978', '75182', '32941', '34484', '85351', '29658', '92704', '03773', '08003', '33432', '74146', '62933', '14228', '75173', '71302', '48906', '94613', '34957', '34602', '21130', '11733', '34233', '17313', '84090', '47036', '22101', '14092', '15478', '34243', '95350', '48324', '28364', '08554', '20158', '06035', '20151', '89150', '85329', '32719', '90013', '22193', '59748', '03455', '94533', '21734', '37806', '13157', '27360', '94140', '16505', '85336', '63019', '43157', '45140', '63348', '80129', '33026', '48157', '61238', '10994', '45479', '10578', '14838', '91913', '33764', '91723', '60064', '16024', '76163', '63016', '38168', '77080', '84335', '55121', '13211', '03868', '12123', '47971', '28712', '37927', '95672', '40504', '21144', '35022', '12201', '08831', '08648', '64870', '74029', '75803', '31131', '60632', '44636', '95051', '33156', '94702', '94041', '22911', '71119', '70634', '03048', '29829', '73071', '88220', '35146', '28040', '85053', '98029', '73018', '88347', '08759', '13156', '19057', '80015', '84060', '18953', '97402', '32205', '85029', '43146', '55345', '33972', '22243', '97361', '18321', '14512', '95621', '48458', '35042', '21659', '80915', '48067', '12074', '54123', '61801', '19095', '14904', '29148', '55359', '32614', '91790', '52730', '99205', '89146', '18913', '33674', '19192', '91758', '33710', '37069', '28147', '12170', '53203', '18066', '70039', '74149', '83204', '98292', '78254', '13465', '04282', '15234', '01053', '12187', '19075', '13494', '42127', '60506', '54173', '74881', '05660', '59920', '45346', '17309', '40505', '32413', '29568', '15601', '85372', '77706', '48375', '33618', '01096', '47857', '72843', '44504', '66106', '89432', '97004', '80530', '56472', '01262', '75372', '93637', '20020', '56601', '14040', '92546', '16063', '10605', '08070', '75903', '12435', '23223', '55150', '52302', '19938', '14807', '35501', '30311', '14067', '38824', '15480', '50307', '74037', '92374', '01546', '92126', '47863', '15059', '89423', '06804', '10984', '14748', '30721', '60201', '92707', '29730', '27612', '57064', '14514', '19435', '17043', '46802', '14692', '93305', '47724', '70519', '22033', '52548', '44312', '17540', '76088', '59925', '31093', '06784', '60647', '07017', '33147', '14025', '48820', '08083', '22853', '84152', '19470', '13797', '48919', '45426', '90224', '17402', '17363', '15238', '15202', '12406', '45203', '11420', '48421', '82510', '68134', '18518', '89081', '82009', '16415', '24209', '29420', '95472', '54701', '18044', '44652', '32834', '75087', '56474', '46229', '13748', '07751', '80539', '23072', '32097', '16125', '79703', '48223', '33024', '85236', '33713', '27982', '92056', '10577', '27114', '73028', '08023', '33442', '99516', '93611', '22203', '16262', '44601', '01830', '76524', '34607', '08512', '06795', '32955', '77020', '55442', '08060', '76179', '82070', '91402', '61761', '61705', '07857', '78724', '01242', '18333', '21401', '20744', '73110', '53220', '42327', '92083', '12212', '76542', '15312', '45222', '17318', '95354', '29693', '19428', '95336', '11955', '30445', '94925', '32803', '19152', '84664', '10037', '67868', '23505', '76504', '07514', '45371', '10009', '32209', '77061', '78123', '19022', '99338', '03086', '41014', '14070', '10459', '01611', '93385', '90028', '19408', '13408', '20707', '92373', '52802', '21050', '19457', '14225', '20903', '85381', '31331', '73644', '29576', '02350', '16826', '29566', '78852', '46637', '38001', '95136', '10933', '72436', '33167', '43615', '53050', '91942', '28470', '36854', '77258', '31721', '72952', '55775', '62521', '45692', '63143', '07302', '66049', '48317', '54964', '15463', '30080', '30458', '93420', '55945', '22043', '33010', '85268', '55327', '89410', '32332', '19013', '10460', '46928', '35183', '27829', '32168', '23187', '12404', '12472', '14038', '28034', '76632', '85033', '92637', '02210', '19943', '95335', '44818', '85750', '01965', '62084', '12810', '15474', '32506', '02458', '59604', '19550', '31503', '97639', '18644', '79911', '32226', '78389', '46259', '13651', '76140', '84339', '99521', '60018', '60006', '35801', '70374', '60016', '46226', '75057', '50673', '91313', '28804', '02115', '12456', '21237', '47713', '33615', '96002', '61848', '82801', '36250', '46240', '62663', '19112', '15360', '15691', '40536', '95547', '42366', '30237', '13744', '34758', '31604', '71256', '94803', '70640', '32968', '72061', '31220', '37912', '74804', '23060', '15227', '43125', '95645', '79603', '55987', '75187', '19405', '48841', '54247', '33169', '03867', '73443', '76205', '13153', '08008', '42501', '32241', '49905', '13492', '33825', '53928', '78205', '43004', '37847', '89106', '77066', '90001', '46077', '38177', '37769', '55318', '12308', '28650', '85302', '70145', '35981', '27817', '17109', '90037', '12524', '76103', '06457', '20861', '34289', '03774', '59926', '73149', '79511', '62544', '36305', '54902', '94521', '48211', '17970', '15088', '95655', '11226', '63954', '02301', '48842', '45419', '44087', '95442', '41091', '45662', '75229', '45805', '20675', '99324', '49017', '76106', '34987', '44307', '80917', '46804', '71701', '15052', '05673', '77705', '89703', '53092', '95153', '49418', '73507', '17069', '68776', '01097', '35206', '08346', '90503', '11965', '98446', '19130', '80923', '54207', '20723', '17721', '93311', '17740', '05402', '60426', '18331', '83607', '01330', '27514', '45458', '86302', '94581', '37219', '80601', '71754', '44121', '01260', '28306', '46011', '12564', '34212', '78725', '94117', '38756', '92154', '75167', '68521', '08012', '44708', '14054', '93033', '30106', '95680', '79925', '19352', '10027', '06702', '15216', '24527', '16210', '92108', '13640', '11769', '55123', '28529', '89508', '23230', '16354', '27828', '80602', '80526', '44062', '15710', '08098', '81501', '11235', '23238', '04077', '12025', '94105', '34282', '28731', '02188', '86409', '08832', '74873', '48851', '61233', '96001', '07842', '17747', '10931', '28211', '52248', '32605', '85041', '39565', '29457', '34232', '38238', '93256', '46929', '97230', '98901', '63945', '49201', '11411', '16256', '98559', '17527', '03221', '11237', '61265', '98266', '92018', '39740', '85326', '84089', '68059', '61820', '77058', '71292', '64133', '17051', '03109', '19453', '28692', '29412', '19078', '43164', '17762', '17365', '28612', '02468', '05758', '32117', '49341', '11367', '11239', '77836', '55357', '97478', '76366', '96740', '86004', '88030', '91746', '70755', '30324', '19472', '95122', '33904', '43055', '33803', '36117', '90405', '55446', '38024', '30101', '05454', '51340', '53726', '32560', '15688', '02474', '14052', '78244', '89523', '13030', '74401', '17830', '98001', '38128', '34668', '48043', '44682', '17221', '80227', '48377', '93160', '02135', '77077', '92868', '29456', '31204', '94807', '92674', '28227', '15470', '46517', '49022', '68959', '44640', '78002', '67204', '50007', '46121', '79413', '24014', '36453', '13483', '92832', '01244', '15021', '95842', '75260', '02446', '04109', '06510', '02718', '86314', '99645', '60656', '53525', '49788', '30354', '55786', '77254', '37923', '33993', '92171', '18845', '12965', '78615', '73105', '95670', '13317', '33682', '17220', '40348', '02140', '12839', '02141', '05149', '74015', '13036', '76071', '27532', '87506', '85271', '33647', '43162', '21286', '06793', '37215', '12531', '05742', '15082', '72718', '02808', '31401', '92618', '95011', '19121', '06479', '15060', '05062', '52245', '14098', '63304', '35243', '02645', '35824', '13811', '89151', '29485', '46562', '13320', '04032', '10310', '08031', '94538', '11233', '33144', '19119', '20227', '53218', '83854', '20688', '53095', '80247', '11432', '19382', '22952', '48120', '33185', '98520', '13605', '34202', '11030', '30097', '77357', '80202', '67217', '28786', '78215', '89118', '44460', '75125', '67060', '33463', '35957', '68102', '23434', '30110', '20640', '49441', '34787', '41005', '75069', '11558', '89407', '18334', '17703', '92592', '27201', '12031', '58058', '16110', '55311', '80212', '61815', '03819', '44815', '27591', '34102', '95688', '30175', '14030', '34465', '95821', '33435', '92805', '10461', '55374', '15774', '43204', '15347', '07726', '83429', '93720', '84721', '20871', '06810', '71203', '19701', '13485', '58503', '98675', '91785', '18337', '84128', '04489', '15940', '66223', '95116', '83256', '85079', '08350', '21704', '55026', '57702', '85382', '32318', '16410', '68803', '45207', '48834', '93412', '05777', '60083', '45171', '21075', '12165', '55416', '14720', '95616', '93301', '98252', '14872', '62959', '25420', '13694', '66607', '85206', '45301', '77056', '77401', '90210', '34420', '16668', '33905', '77044', '31636', '29151', '53716', '87571', '88061', '47356', '43085', '13044', '34743', '47303', '16651', '60804', '49515', '99502', '80427', '92705', '20110', '16046', '61260', '60421', '03839', '33076', '95531', '46033', '08085', '55427', '79104', '63032', '44862', '14564', '34990', '15066', '13103', '22201', '92029', '01901', '33830', '55347', '89521', '15722', '94501', '52403', '92139', '34216', '46904', '38762', '97627', '72626', '33178', '18104', '95758', '14173', '19440', '21710', '15333', '68503', '93204', '10587', '18707', '30084', '85037', '01062', '44809', '36801', '91116', '30815', '19977', '89137', '61109', '40475', '33704', '44311', '99507', '60642', '85618', '46225', '97404', '33772', '32819', '12574', '23453', '28326', '07735', '15713', '94904', '27568', '46131', '43021', '61008', '05650', '08853', '95207', '11385', '34104', '11956', '66227', '94560', '43735', '84170', '66048', '14028', '17327', '76533', '45216', '63022', '90743', '94942', '75241', '19058', '32621', '40229', '47421', '79424', '79124', '91384', '38004', '35055', '15223', '16222', '95628', '55005', '33635', '06060', '41056', '07435', '62234', '61108', '63005', '92072', '12475', '23707', '70125', '33778', '61602', '15422', '31005', '85086', '71913', '48088', '19607', '80502', '06250', '72012', '37205', '17737', '79916', '63752', '43739', '12953', '43017', '02114', '34690', '63080', '02020', '90715', '51301', '38651', '63102', '29365', '33629', '20872', '37204', '07834', '31050', '18902', '92610', '04074', '75062', '53562', '17949', '06120', '11972', '28098', '78539', '92655', '46750', '94147', '97214', '27529', '40243', '35111', '21718', '16402', '07838', '81326', '16648', '20674', '53128', '68601', '01104', '24122', '75153', '14139', '70047', '63852', '76250', '68114', '44484', '77662', '07504', '97204', '27539', '60563', '34208', '23116', '93291', '76126', '11948', '77584', '62972', '32129', '07876', '18221', '06519', '21146', '45377', '37220', '77316', '83864', '17337', '61281', '13352', '69101', '15057', '93669', '35136', '66763', '36345', '32935', '95365', '32724', '16511', '97218', '35988', '48154', '94953', '99157', '77904', '39503', '07878', '80137', '22192', '08033', '28077', '43502', '06281', '14462', '19465', '61316', '19142', '98394', '16738', '93245', '16404', '85929', '29320', '76155', '43608', '43952', '64152', '74423', '13664', '22034', '33914', '30805', '77546', '28207', '08001', '05043', '15017', '44077', '35904', '99501', '02492', '92391', '17545', '03756', '60069', '40769', '15068', '05067', '02467', '42339', '18103', '33155', '79403', '12546', '46619', '48439', '15340', '80920', '30501', '44437', '18829', '15215', '19002', '33931', '32444', '15610', '17244', '95835', '60178', '28806', '20717', '21705', '77033', '92127', '97317', '12518', '12441', '37921', '85373', '44301', '07083', '71075', '11214', '19110', '01082', '34674', '97429', '10956', '63801', '37804', '18065', '50321', '03233', '11694', '34603', '11727', '53056', '20794', '50158', '37398', '07103', '72065', '33847', '33907', '03905', '14061', '04228', '10550', '28378', '43412', '75137', '16744', '62695', '34608', '35071', '96786', '46063', '75114', '33179', '28376', '32833', '75209', '77031', '01038', '18623', '46356', '89183', '02813', '11217', '62085', '55386', '48607', '01022', '61615', '57754', '18101', '08527', '10013', '41017', '95132', '29484', '98233', '84660', '14069', '91362', '98408', '17316', '23451', '02646', '10509', '07440', '62901', '10032', '55303', '46216', '39232', '98662', '80017', '76016', '28803', '92585', '15685', '98092', '61257', '06263', '17271', '34210', '98312', '98003', '46222', '91768', '76114', '75035', '12821', '32730', '75126', '07846', '15656', '11413', '44721', '85269', '13803', '94545', '84171', '28451', '64068', '36561', '40165', '29544', '98155', '07416', '77979', '47714', '27103', '01201', '13859', '95337', '60669', '75961', '91003', '75204', '06248', '47542', '37918', '77099', '89087', '76252', '60613', '48864', '03603', '33070', '28079', '40065', '01223', '54980', '57104', '15955', '75212', '06073', '23701', '12489', '33328', '16416', '44108', '14613', '87505', '17547', '20108', '14172', '27517', '35630', '12541', '16510', '30350', '77030', '47802', '24219', '93523', '94939', '95117', '21702', '10940', '21228', '63122', '70075', '19310', '30297', '06241', '85073', '78258', '33805', '33605', '12037', '80231', '30049', '64139', '15459', '02027', '85257', '49501', '80216', '35504', '14544', '22627', '45103', '43213', '07753', '64163', '94065', '12879', '78240', '68122', '01107', '39110', '07511', '17266', '08809', '24121', '13402', '13459', '15921', '04336', '54928', '97030', '43963', '34103', '93105', '03278', '68526', '02145', '78381', '19128', '40023', '10960', '32025', '18640', '79367', '72335', '38501', '56361', '80819', '89449', '07421', '10090', '45840', '53031', '48227', '10969', '15010', '60510', '41042', '08049', '37211', '94111', '94558', '35613', '10510', '45230', '18083', '33952', '78006', '19904', '11771', '05772', '32092', '20907', '35226', '16879', '11755', '15928', '16329', '63855', '52757', '13411', '48128', '19711', '95356', '21052', '64036', '39158', '12024', '37716', '10542', '15207', '30022', '95205', '02576', '94605', '04102', '13787', '89138', '33595', '45219', '60519', '05086', '90004', '16345', '37048', '98562', '08901', '27012', '19605', '18928', '89533', '35503', '42321', '95485', '12526', '75034', '33875', '90068', '33762', '43635', '35816', '94588', '98536', '80207', '66215', '04047', '07082', '01824', '06824', '85757', '78592', '54128', '28372', '95526', '11783', '12446', '03810', '31557', '05056', '76104', '10010', '44117', '95978', '04210', '05744', '70816', '80120', '52732', '27616', '28001', '73045', '95830', '64131', '92552', '92683', '17039', '

In [19]:

joined1= pd.merge(house_df, pop_df_unique, left_on='zipcode', right_on='zips', how='left') 
joined1.shape

(7561517, 98)

In [45]:
joined1.drop_duplicates()

,period_begin,period_end,period_duration,region_type_id,table_id,is_seasonally_adjusted,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,...,density,source,military,incorporated,cdp,timezone,ranking,zips,id,age_median,male,female,married,family_size,income_household_median,income_household_six_figure,home_ownership,home_value,rent_median,education_college_or_above,labor_force_participation,unemployment_rate,race_white,race_black,race_asian,race_native,race_pacific,race_other,race_multiple
0,2018-12-01,2019-02-28,90,2,24614,f,South Dakota,SD,All Residential,-1,213500.0,0.010651,0.047853,219700.0,0.028077,0.051699,117.252931,0.001910,0.057700,118.767145,0.006820,0.027307,111.0,-0.207143,-0.146154,19.0,-0.050000,-0.173913,122.0,...,906.1,shape,False,True,False,America/Chicago,2.0,57106,1.840003e+09,34.5,50.2,49.8,48.6,3.03,66761.0,29.1,60.3,217707.0,892.0,36.0,74.1,2.5,82.3,6.8,2.5,1.8,0.1,1.1,5.5
1,2018-12-01,2019-02-28,90,2,24614,f,South Dakota,SD,All Residential,-1,213500.0,0.010651,0.047853,219700.0,0.028077,0.051699,117.252931,0.001910,0.057700,118.767145,0.006820,0.027307,111.0,-0.207143,-0.146154,19.0,-0.050000,-0.173913,122.0,...,564.4,shape,False,True,False,America/Chicago,3.0,57106,1.840003e+09,30.3,50.9,49.1,64.5,3.17,91544.0,46.4,65.5,229581.0,999.0,42.0,87.1,1.3,96.6,0.5,1.1,0.2,0.0,0.0,1.6
2,2016-04-01,2016-06-30,90,2,5033,f,New York,NY,Single Family Residential,6,199350.0,0.038281,0.092628,249900.0,0.135909,0.075301,116.488459,0.078156,0.029912,120.108745,-0.004497,0.008726,78.0,0.238095,0.083333,26.0,0.238095,-0.434783,116.0,...,458.0,shape,False,False,False,America/New_York,3.0,14086,1.840004e+09,45.9,49.3,50.7,53.2,2.92,79908.0,37.9,78.0,194941.0,871.0,35.4,67.2,3.1,96.0,1.8,0.7,0.0,0.0,0.2,1.2
3,2016-04-01,2016-06-30,90,2,5033,f,New York,NY,Single Family Residential,6,199350.0,0.038281,0.092628,249900.0,0.135909,0.075301,116.488459,0.078156,0.029912,120.108745,-0.004497,0.008726,78.0,0.238095,0.083333,26.0,0.238095,-0.434783,116.0,...,153.5,shape,False,False,True,America/New_York,3.0,14086,1.840004e+09,42.6,45.1,54.9,56.6,2.87,86250.0,39.2,88.0,197274.0,1230.0,20.9,63.6,1.3,95.3,0.1,2.9,0.0,0.0,0.1,1.6
4,2019-10-01,2019-12-31,90,2,17977,f,Ohio,OH,Single Family Residential,6,183887.0,0.152897,0.339796,154900.0,0.000000,0.240192,85.034221,0.126302,-0.079074,94.455316,0.000000,-0.044860,10.0,0.111111,0.000000,5.0,4.000000,4.000000,11.0,...,160.2,shape,False,True,False,America/New_York,3.0,43044,1.840012e+09,45.2,49.4,50.6,64.8,2.74,64375.0,15.4,84.6,127981.0,950.0,14.7,67.6,6.3,97.6,0.0,0.0,0.0,0.0,0.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10857905,2017-01-01,2017-03-31,90,2,7605,f,Pennsylvania,PA,Townhouse,13,123000.0,0.000000,0.128440,119900.0,0.000000,0.000000,85.416667,0.000000,0.200320,88.315789,0.024471,-0.015194,3.0,-0.400000,0.500000,3.0,NaN,0.500000,11.0,...,58.6,shape,False,False,False,America/New_York,4.0,19522,1.840144e+09,42.4,50.2,49.8,51.7,3.22,66324.0,26.9,78.8,203477.0,1064.0,17.4,64.8,1.4,96.6,0.4,0.0,0.0,0.0,0.2,2.8
10857906,2017-01-01,2017-03-31,90,2,7605,f,Pennsylvania,PA,Townhouse,13,123000.0,0.000000,0.128440,119900.0,0.000000,0.000000,85.416667,0.000000,0.200320,88.315789,0.024471,-0.015194,3.0,-0.400000,0.500000,3.0,NaN,0.500000,11.0,...,489.5,shape,False,False,True,America/New_York,3.0,19522,1.840026e+09,48.7,58.8,41.2,66.4,2.90,64044.0,6.0,76.2,NaN,NaN,12.2,41.1,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
10857907,2017-01-01,2017-03-31,90,2,7605,f,Pennsylvania,PA,Townhouse,13,123000.0,0.000000,0.128440,119900.0,0.000000,0.000000,85.416667,0.000000,0.200320,88.315789,0.024471,-0.015194,3.0,-0.400000,0.500000,3.0,NaN,0.500000,11.0,...,32.5,shape,False,False,True,America/New_York,3.0,19522,1.840035e+09,36.6,60.7,39.3,72.0,2.74,131146.0,61.2,100.0,NaN,NaN,22.1,81.3,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
10857908,2020-02-01,2020-04-30,90,2,7202,f,Pennsylvania,PA,All Residential,-1,60000.0,0.000000,NaN,NaN,NaN,NaN,32.258065,0.000000,NaN,NaN,NaN,NaN,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,...,2485.5,shape,False,True,False,America/New_York,2.0,18762,1.840001e+09,34.7,49.1,50.9,33.6,3.14,42430.0,12.9,47.9,84717.0,826.0,18.6,57.0,8.1,61.8,12.8,2.7,0.2,0.5,11.9,10.3
10857909,2015-12-01,2016-02-29,90,2,26839,f,Illinois,IL,Single Family Residential,6,76750.0,0.300847,6.309524,37000.0,-0.382819,1.960000,39.849320,0.197639,4.271938,24.666667,-0.187396,1.870303,6.0,2.000000,0.500000,NaN,NaN,NaN,3.0,...,241.3,shape,False,True,False,America/Chicago,3.0,62240,1.840013e+09,40.9,45.5,54.5,33.3,3.08,47357.0,15.4,64.0,88934.0,866.0,17.2,69.3,8.7,94.1,4.5,0.0,0.0,0.0,0.0,1.4

In [20]:
joined1.shape

(7561517, 98)

In [21]:
# Drop the 'zipcode' column from the joined dataframe, as it's redundant
joined1 = joined1.drop(columns=['zips'])

# Drop all duplicate rows in the dataframe
joined1 = joined1.drop_duplicates()

In [22]:

joined1.shape

(7561517, 97)

In [23]:
joined1.head()

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,...,population_proper,density,source,military,incorporated,cdp,timezone,ranking,id,age_median,male,female,married,family_size,income_household_median,income_household_six_figure,home_ownership,home_value,rent_median,education_college_or_above,labor_force_participation,unemployment_rate,race_white,race_black,race_asian,race_native,race_pacific,race_other,race_multiple
0,2018-12-01,2019-02-28,90,zip code,2,24614,f,Zip Code: 57106,South Dakota,SD,All Residential,-1,213500.0,0.010651,0.047853,219700.0,0.028077,0.051699,117.252931,0.001910,0.057700,118.767145,0.006820,0.027307,111.0,-0.207143,-0.146154,19.0,-0.050000,...,189258.0,906.1,shape,False,True,False,America/Chicago,2.0,1.840003e+09,34.5,50.2,49.8,48.6,3.03,66761.0,29.1,60.3,217707.0,892.0,36.0,74.1,2.5,82.3,6.8,2.5,1.8,0.1,1.1,5.5
1,2016-04-01,2016-06-30,90,zip code,2,5033,f,Zip Code: 14086,New York,NY,Single Family Residential,6,199350.0,0.038281,0.092628,249900.0,0.135909,0.075301,116.488459,0.078156,0.029912,120.108745,-0.004497,0.008726,78.0,0.238095,0.083333,26.0,0.238095,...,44732.0,458.0,shape,False,False,False,America/New_York,3.0,1.840004e+09,45.9,49.3,50.7,53.2,2.92,79908.0,37.9,78.0,194941.0,871.0,35.4,67.2,3.1,96.0,1.8,0.7,0.0,0.0,0.2,1.2
2,2019-10-01,2019-12-31,90,zip code,2,17977,f,Zip Code: 43044,Ohio,OH,Single Family Residential,6,183887.0,0.152897,0.339796,154900.0,0.000000,0.240192,85.034221,0.126302,-0.079074,94.455316,0.000000,-0.044860,10.0,0.111111,0.000000,5.0,4.000000,...,83.0,160.2,shape,False,True,False,America/New_York,3.0,1.840012e+09,45.2,49.4,50.6,64.8,2.74,64375.0,15.4,84.6,127981.0,950.0,14.7,67.6,6.3,97.6,0.0,0.0,0.0,0.0,0.0,2.4
3,2022-06-01,2022-08-31,90,zip code,2,16419,f,Zip Code: 38611,Mississippi,MS,All Residential,-1,340000.0,0.000000,0.357285,349250.0,-0.168254,0.042693,157.297576,-0.006996,0.248393,162.105758,-0.007313,0.176632,43.0,-0.044444,0.228571,17.0,0.307692,...,1605.0,84.2,shape,False,False,True,America/Chicago,3.0,1.840075e+09,31.1,50.4,49.6,37.8,2.79,NaN,25.1,100.0,NaN,NaN,5.1,59.0,0.0,82.6,0.0,0.0,0.0,0.0,17.4,0.0
4,2019-09-01,2019-11-30,90,zip code,2,20397,f,Zip Code: 48034,Michigan,MI,Single Family Residential,6,231650.0,-0.034389,-0.172679,299900.0,-0.000167,0.100752,94.444444,-0.029666,-0.089638,119.750000,0.024105,0.223819,11.0,-0.153846,0.100000,2.0,-0.333333,...,76196.0,1120.6,shape,False,True,False,America/Detroit,3.0,1.840002e+09,41.5,46.3,53.7,35.6,3.11,60006.0,25.5,49.4,177589.0,1172.0,38.8,61.0,7.4,24.5,66.7,1.7,0.1,0.1,0.6,6.3

In [24]:

colnames = joined1.columns.tolist()


# This will give you a list of column names
print(colnames)

['period_begin', 'period_end', 'period_duration', 'region_type', 'region_type_id', 'table_id', 'is_seasonally_adjusted', 'region', 'state', 'state_code', 'property_type', 'property_type_id', 'median_sale_price', 'median_sale_price_mom', 'median_sale_price_yoy', 'median_list_price', 'median_list_price_mom', 'median_list_price_yoy', 'median_ppsf', 'median_ppsf_mom', 'median_ppsf_yoy', 'median_list_ppsf', 'median_list_ppsf_mom', 'median_list_ppsf_yoy', 'homes_sold', 'homes_sold_mom', 'homes_sold_yoy', 'pending_sales', 'pending_sales_mom', 'pending_sales_yoy', 'new_listings', 'new_listings_mom', 'new_listings_yoy', 'inventory', 'inventory_mom', 'inventory_yoy', 'months_of_supply', 'months_of_supply_mom', 'months_of_supply_yoy', 'median_dom', 'median_dom_mom', 'median_dom_yoy', 'avg_sale_to_list', 'avg_sale_to_list_mom', 'avg_sale_to_list_yoy', 'sold_above_list', 'sold_above_list_mom', 'sold_above_list_yoy', 'price_drops', 'price_drops_mom', 'price_drops_yoy', 'off_market_in_two_weeks', 'off_market_in_two_weeks_mom', 'off_market_in_two_weeks_yoy', 'parent_metro_region', 'parent_metro_region_metro_code', 'last_updated', 'zipcode', 'city', 'state_id', 'state_name', 'county_fips', 'county_name', 'county_fips_all', 'county_name_all', 'lat', 'lng', 'population', 'population_proper', 'density', 'source', 'military', 'incorporated', 'cdp', 'timezone', 'ranking', 'id', 'age_median', 'male', 'female', 'married', 'family_size', 'income_household_median', 'income_household_six_figure', 'home_ownership', 'home_value', 'rent_median', 'education_college_or_above', 'labor_force_participation', 'unemployment_rate', 'race_white', 'race_black', 'race_asian', 'race_native', 'race_pacific', 'race_other', 'race_multiple']

In [25]:
#Just want 30 cols
columns_extract = [
    'period_begin','period_end','period_duration','zipcode', 'state','city',
    'median_sale_price', 'median_sale_price_mom', 'median_sale_price_yoy',
    'median_list_price', 'median_list_price_mom', 'median_list_price_yoy',
    'median_ppsf', 'median_ppsf_mom', 'median_ppsf_yoy', 'homes_sold',
    'homes_sold_mom', 'inventory', 'inventory_mom', 'median_dom',
    'population', 'population_proper', 'density', 'income_household_median',
    'labor_force_participation', 'unemployment_rate', 'education_college_or_above',
    'home_ownership', 'home_value', 'rent_median', 'median_list_ppsf',
    'new_listings', 'new_listings_mom', 'months_of_supply', 'avg_sale_to_list',
    'sold_above_list'
]

# Extract these columns from joined1 DataFrame
extracted_df = joined1[columns_extract]

# Display the first few rows of the extracted dataframe
extracted_df.head()

,period_begin,period_end,period_duration,zipcode,state,city,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,homes_sold,homes_sold_mom,inventory,inventory_mom,median_dom,population,population_proper,density,income_household_median,labor_force_participation,unemployment_rate,education_college_or_above,home_ownership,home_value,rent_median,median_list_ppsf,new_listings,new_listings_mom,months_of_supply,avg_sale_to_list,sold_above_list
0,2018-12-01,2019-02-28,90,57106,South Dakota,Sioux Falls,213500.0,0.010651,0.047853,219700.0,0.028077,0.051699,117.252931,0.001910,0.057700,111.0,-0.207143,162.0,0.087248,81.0,204484.0,189258.0,906.1,66761.0,74.1,2.5,36.0,60.3,217707.0,892.0,118.767145,122.0,0.109091,NaN,0.979745,0.135135
1,2016-04-01,2016-06-30,90,14086,New York,Lancaster,199350.0,0.038281,0.092628,249900.0,0.135909,0.075301,116.488459,0.078156,0.029912,78.0,0.238095,97.0,0.141176,54.0,44732.0,44732.0,458.0,79908.0,67.2,3.1,35.4,78.0,194941.0,871.0,120.108745,116.0,0.017544,NaN,0.983976,0.346154
2,2019-10-01,2019-12-31,90,43044,Ohio,Mutual,183887.0,0.152897,0.339796,154900.0,0.000000,0.240192,85.034221,0.126302,-0.079074,10.0,0.111111,6.0,-0.571429,66.0,83.0,83.0,160.2,64375.0,67.6,6.3,14.7,84.6,127981.0,950.0,94.455316,11.0,0.000000,NaN,0.990772,0.200000
3,2022-06-01,2022-08-31,90,38611,Mississippi,Victoria,340000.0,0.000000,0.357285,349250.0,-0.168254,0.042693,157.297576,-0.006996,0.248393,43.0,-0.044444,28.0,0.037037,6.5,1605.0,1605.0,84.2,NaN,59.0,0.0,5.1,100.0,NaN,NaN,162.105758,50.0,-0.074074,NaN,1.003796,0.395349
4,2019-09-01,2019-11-30,90,48034,Michigan,Southfield,231650.0,-0.034389,-0.172679,299900.0,-0.000167,0.100752,94.444444,-0.029666,-0.089638,11.0,-0.153846,9.0,0.500000,28.0,76196.0,76196.0,1120.6,60006.0,61.0,7.4,38.8,49.4,177589.0,1172.0,119.750000,13.0,0.083333,NaN,0.953366,0.181818

In [26]:
#extract shape
extracted_df.shape

(7561517, 36)

In [27]:
#filter joined df to only East Coast before combining with quality df 
 # List of East Coast states
east_coast_states = [
    "Maine", "New Hampshire", "Massachusetts", "Rhode Island", "Connecticut",
    "New York", "New Jersey", "Delaware", "Maryland", "Virginia",
    "North Carolina", "South Carolina", "Georgia", "Florida"
]

# Filter  DataFrame for rows where the 'state' column matches the East Coast states
east_house_pop = extracted_df[extracted_df['state'].isin(east_coast_states)]

# Display
east_house_pop.shape

(2541426, 36)

In [28]:
#run sample so only 1,000,000 rows 
sampled_df = east_house_pop.sample(n=1200000, random_state=1)

In [30]:
#lifequality df
quality_df= pd.read_csv("/Users/amelchristy/Desktop/Python_Project/Real_Estate_Lehigh/life_quality_state.csv")

In [31]:
quality_df.head()

,fips,state,densityMi,pop2023,pop2022,pop2020,pop2019,pop2010,growthRate,growth,growthSince2010,QualityOfLifeTotalScore,QualityOfLifeQualityOfLife,QualityOfLifeAffordability,QualityOfLifeEconomy,QualityOfLifeEducationAndHealth,QualityOfLifeSafety
0,1,Alabama,100.67620,5098746,5074296,5031362,5006199.4,4779736,0.00482,24450,0.06674,45.61,40,1,40,48,32
1,2,Alaska,1.28449,732984,733583,732923,730653.8,710231,-0.00082,-599,0.03204,40.93,50,42,22,30,45
2,4,Arizona,65.61541,7453517,7359197,7179943,7101150.4,6392017,0.01282,94320,0.16607,48.31,21,25,14,39,40
3,5,Arkansas,58.86715,3063152,3045637,3014195,3004367.3,2915918,0.00575,17515,0.05049,42.42,46,4,34,45,47
4,6,California,249.81347,38915693,39029342,39501653,39276883.3,37253956,-0.00291,-113649,0.04461,52.03,2,50,15,24,27

In [32]:
quality_df.keys()

Index(['fips', 'state', 'densityMi', 'pop2023', 'pop2022', 'pop2020',
       'pop2019', 'pop2010', 'growthRate', 'growth', 'growthSince2010',
       'QualityOfLifeTotalScore', 'QualityOfLifeQualityOfLife',
       'QualityOfLifeAffordability', 'QualityOfLifeEconomy',
       'QualityOfLifeEducationAndHealth', 'QualityOfLifeSafety'],
      dtype='object')

In [33]:
quality_df= quality_df[['state','pop2023','pop2022','pop2020','pop2019','pop2010','growthRate','growth','growthSince2010','QualityOfLifeTotalScore']]

In [36]:
#joined
joined2= pd.merge(sampled_df,quality_df, left_on ='state', right_on='state', how='left')

In [37]:
joined2.shape

(1200000, 45)

In [38]:
joined2.keys
#export to csv

<bound method NDFrame.keys of         period_begin  period_end  period_duration zipcode        state  \
0         2023-05-01  2023-07-31               90   13790     New York
1         2017-11-01  2018-01-31               90   30360      Georgia
2         2017-11-01  2018-01-31               90   14475     New York
3         2015-08-01  2015-10-31               90   07087   New Jersey
4         2019-06-01  2019-08-31               90   31501      Georgia
...              ...         ...              ...     ...          ...
1199995   2022-08-01  2022-10-31               90   32351      Florida
1199996   2017-05-01  2017-07-31               90   06478  Connecticut
1199997   2014-07-01  2014-09-30               90   32084      Florida
1199998   2016-07-01  2016-09-30               90   21638     Maryland
1199999   2016-09-01  2016-11-30               90   33184      Florida

                    city  median_sale_price  median_sale_price_mom  \
0                  Union           192500.0               1.264706
1               Dunwoody           323500.0               0.042036
2        West Bloomfield           500000.0               0.000000
3                    NaN           240500.0              -0.141071
4               Waycross            91000.0              -0.021505
...                  ...                ...                    ...
1199995           Quincy           140000.0               0.000000
1199996              NaN           358638.0              -0.038375
1199997    St. Augustine           193740.0               0.025079
1199998     Kent Narrows           343500.0              -0.032394
1199999          Tamiami           144000.0               0.000000

         median_sale_price_yoy  median_list_price  median_list_price_mom  \
0                    -0.490741           219000.0               0.406100
1                     0.094755           356700.0               0.080909
2                          NaN           419900.0               0.000000
3                          NaN           239000.0               0.201005
4                    -0.436533           114950.0               0.259726
...                        ...                ...                    ...
1199995                    NaN                NaN                    NaN
1199996              -0.082585           377012.5              -0.013121
1199997              -0.026432           189995.0               0.020107
1199998               0.008811           350000.0              -0.156525
1199999               0.238710           157450.0               0.049982

         median_list_price_yoy  median_ppsf  median_ppsf_mom  median_ppsf_yoy  \
0                     1.844156    45.151413        -0.025792         0.204702
1                     0.189004   142.857143        -0.033792         0.011025
2                          NaN   116.495806         0.000000              NaN
3                          NaN   170.007699        -0.226172              NaN
4                    -0.298444    62.126866        -0.064607         0.220476
...                        ...          ...              ...              ...
1199995                    NaN    81.018519         0.000000              NaN
1199996              -0.038724   189.663462        -0.029717         0.132119
1199997              -0.040490   110.119048         0.043868         0.081994
1199998               0.219725   173.313497         0.012646         0.091223
1199999               0.081387   150.502787         0.051847         0.063441

         homes_sold  homes_sold_mom  inventory  inventory_mom  median_dom  \
0               2.0        1.000000        2.0       0.000000        78.5
1              37.0       -0.075000       32.0      -0.111111        22.0
2               1.0        0.000000        1.0      -0.500000       114.0
3              12.0        0.090909       12.0       0.090909        24.5
4               4.0        0.333333       15.0       0.071429        43.0
...             ...             ...        ...            ...         ...
1199995         2.0        0.000000        NaN            NaN       103.5
1199996         7.0       -0.125000       19.0      -0.173913        50.0
1199997       131.0        0.073770      207.0       0.014706       109.0
1199998        32.0        0.103448       37.0      -0.051282        64.0
1199999        11.0        0.222222        4.0       0.000000        19.0

         population  population_proper  density  income_household_median  \
0           56047.0            56047.0    610.7                  52410.0
1           51103.0            51103.0   1514.7                  97868.0
2            2725.0             2725.0     41.3                  56324.0
3               NaN                NaN      NaN                      NaN
4           13898.0            13898.0    452.2                  31151.0
...             ...                ...      ...                      ...
1199995      8038.0             8038.0    266.4                  31756.0
1199996         NaN                NaN      NaN                      NaN
1199997     97703.0            13994.0    567.5                  67269.0
1199998       509.0              509.0    208.8                 106196.0
1199999     54525.0            54525.0   3016.6                  65355.0

         labor_force_participation  unemployment_rate  \
0                             59.5                6.9
1                             68.8                2.2
2                             61.0                7.1
3                              NaN                NaN
4                             44.9                5.1
...                            ...                ...
1199995                       45.6                2.2
1199996                        NaN                NaN
1199997                       55.1                3.9
1199998                       41.3               10.5
1199999                       63.1                3.3

         education_college_or_above  home_ownership  home_value  rent_median  \
0                              30.5            61.2    116820.0        800.0
1                              71.3            54.3    468026.0       1610.0
2                              24.1            90.4    149145.0        829.0
3                               NaN             NaN         NaN          NaN
4                              17.3            44.2     69315.0        662.0
...                             ...             ...         ...          ...
1199995                        16.9            64.2     90695.0        681.0
1199996                         NaN             NaN         NaN          NaN
1199997                        41.6            65.7    312726.0       1217.0
1199998                        49.7            86.0    561482.0       2219.0
1199999                        32.1            72.8    340762.0       1693.0

         median_list_ppsf  new_listings  new_listings_mom  months_of_supply  \
0               93.112245           3.0         -0.250000               NaN
1              152.403058          34.0         -0.346154               NaN
2              169.382816           1.0          0.000000               NaN
3              173.326673          11.0         -0.083333               NaN
4               72.408078           8.0          0.000000               NaN
...                   ...           ...               ...               ...
1199995               NaN           NaN               NaN               NaN
1199996        186.994402          18.0          0.058824               NaN
1199997        116.533865         126.0         -0.066667               NaN
1199998        181.049177          22.0         -0.388889               NaN
1199999        155.890171           8.0         -0.333333               NaN

         avg_sale_to_list  sold_above_list   pop2023   pop2022   pop2020  \
0                0.929679         0.000000  19496810  19677151  20108296
1                0.983099         0.162162  11037723  10912876  10729828
2                0.909091         0.000000  19496810  19677151  20108296
3                0.976871         0.333333   9255437   9261699   9271689
4                1.009777         0.250000  11037723  10912876  10729828
...                   ...              ...       ...       ...       ...
1199995          0.886076         0.000000  22661577  22244823  21589602
1199996          0.981824         0.142857   3629055   3626205   3597362
1199997          0.957627         0.160305  22661577  22244823  21589602
1199998          0.957688         0.125000   6154710   6164660   6173205
1199999          0.987630         0.090909  22661577  22244823  21589602

            pop2019   pop2010  growthRate  growth  growthSince2010  \
0        20035276.6  19378102    -0.00916 -180341          0.00613
1        10625610.5   9687653     0.01144  124847          0.13936
2        20035276.6  19378102    -0.00916 -180341          0.00613
3         9223709.5   8791894    -0.00068   -6262          0.05272
4        10625610.5   9687653     0.01144  124847          0.13936
...             ...       ...         ...     ...              ...
1199995  21310772.8  18801310     0.01873  416754          0.20532
1199996   3595035.5   3574097     0.00079    2850          0.01538
1199997  21310772.8  18801310     0.01873  416754          0.20532
1199998   6133239.7   5773552    -0.00161   -9950          0.06602
1199999  21310772.8  18801310     0.01873  416754          0.20532

         QualityOfLifeTotalScore
0                          60.64
1                          50.76
2                          60.64
3                          62.01
4                          50.76
...                          ...
1199995                    58.07
1199996                    52.21
1199997                    58.07
1199998                    54.40
1199999                    58.07

[1200000 rows x 45 columns]>

In [42]:
#export to csv
joined2.to_csv('sampled_clean.csv')

In [36]:
#make target variable
#What are good metrics for hot area? Population growth?

In [45]:
small_df = joined2.sample(n=200000, random_state=1)

In [46]:
small_df.to_csv('small_clean.csv')

In [47]:
sample_2 = joined2.sample(n=85000, random_state=1)

In [50]:
sample_2.to_csv('smallest_clean_sample.csv')

sample.keys()

In [49]:
sample_2.keys()

Index(['period_begin', 'period_end', 'period_duration', 'zipcode', 'state',
       'city', 'median_sale_price', 'median_sale_price_mom',
       'median_sale_price_yoy', 'median_list_price', 'median_list_price_mom',
       'median_list_price_yoy', 'median_ppsf', 'median_ppsf_mom',
       'median_ppsf_yoy', 'homes_sold', 'homes_sold_mom', 'inventory',
       'inventory_mom', 'median_dom', 'population', 'population_proper',
       'density', 'income_household_median', 'labor_force_participation',
       'unemployment_rate', 'education_college_or_above', 'home_ownership',
       'home_value', 'rent_median', 'median_list_ppsf', 'new_listings',
       'new_listings_mom', 'months_of_supply', 'avg_sale_to_list',
       'sold_above_list', 'pop2023', 'pop2022', 'pop2020', 'pop2019',
       'pop2010', 'growthRate', 'growth', 'growthSince2010',
       'QualityOfLifeTotalScore'],
      dtype='object')

In [53]:
#np.where create target
sample_2.keys()

Index(['period_begin', 'period_end', 'period_duration', 'zipcode', 'state',
       'city', 'median_sale_price', 'median_sale_price_mom',
       'median_sale_price_yoy', 'median_list_price', 'median_list_price_mom',
       'median_list_price_yoy', 'median_ppsf', 'median_ppsf_mom',
       'median_ppsf_yoy', 'homes_sold', 'homes_sold_mom', 'inventory',
       'inventory_mom', 'median_dom', 'population', 'population_proper',
       'density', 'income_household_median', 'labor_force_participation',
       'unemployment_rate', 'education_college_or_above', 'home_ownership',
       'home_value', 'rent_median', 'median_list_ppsf', 'new_listings',
       'new_listings_mom', 'months_of_supply', 'avg_sale_to_list',
       'sold_above_list', 'pop2023', 'pop2022', 'pop2020', 'pop2019',
       'pop2010', 'growthRate', 'growth', 'growthSince2010',
       'QualityOfLifeTotalScore'],
      dtype='object')

In [54]:
sample_2.head()

,period_begin,period_end,period_duration,zipcode,state,city,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,homes_sold,homes_sold_mom,inventory,inventory_mom,median_dom,population,population_proper,density,income_household_median,labor_force_participation,unemployment_rate,education_college_or_above,home_ownership,home_value,rent_median,median_list_ppsf,new_listings,new_listings_mom,months_of_supply,avg_sale_to_list,sold_above_list,pop2023,pop2022,pop2020,pop2019,pop2010,growthRate,growth,growthSince2010,QualityOfLifeTotalScore
209886,2020-12-01,2021-02-28,90,01432,Massachusetts,Devens,192500.0,0.000000,-0.423653,185000.0,0.000000,NaN,225.146199,0.093150,0.063947,1.0,-0.666667,1.0,0.000000,26.0,2071.0,2071.0,117.9,120777.0,30.9,1.2,31.8,100.0,NaN,NaN,191.709845,1.0,-0.50,NaN,1.040541,1.000000,6974258,6981974,6995729,6950919.0,6547629,-0.00111,-7716,0.06516,62.65
599970,2022-04-01,2022-06-30,90,13057,New York,Manlius,290000.0,-0.064214,0.066176,274100.0,-0.037570,0.482423,153.242999,0.114090,0.046329,4.0,-0.200000,2.0,NaN,4.5,33591.0,33591.0,263.9,92371.0,66.5,4.6,52.1,79.8,210262.0,1006.0,153.312475,6.0,2.00,NaN,1.051127,1.000000,19496810,19677151,20108296,20035276.6,19378102,-0.00916,-180341,0.00613,60.64
1108534,2020-03-01,2020-05-31,90,03851,New Hampshire,Milton,220000.0,-0.185185,0.176471,275000.0,-0.049922,0.146311,159.090909,-0.031782,0.404956,17.0,0.133333,19.0,-0.136364,60.0,4503.0,4503.0,52.6,80238.0,69.1,6.4,22.3,88.4,215951.0,900.0,161.422263,23.0,0.15,NaN,0.968807,0.294118,1402957,1395231,1378587,1372375.3,1316470,0.00554,7726,0.06570,58.25
613145,2022-11-01,2023-01-31,90,04444,Maine,NaN,311000.0,-0.142069,0.130909,259900.0,-0.083245,-0.126093,142.170738,-0.002950,-0.082473,12.0,-0.333333,18.0,-0.052632,45.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.203327,14.0,0.00,NaN,0.948276,0.166667,1393442,1385340,1363557,1360037.4,1328361,0.00585,8102,0.04899,57.55
216834,2019-03-01,2019-05-31,90,10461,New York,New York,573500.0,0.052294,0.164479,575000.0,-0.017094,0.117590,300.000000,-0.118531,-0.151363,13.0,0.181818,22.0,0.466667,63.0,18908608.0,8736047.0,11226.2,70663.0,63.4,7.5,39.6,33.2,659738.0,1579.0,383.648687,25.0,0.25,NaN,0.971698,0.076923,19496810,19677151,20108296,20035276.6,19378102,-0.00916,-180341,0.00613,60.64

sample_2.head()

In [60]:
import numpy as np 
#growthrate
#print('min: ',min(sample_2['growthRate']))
#print('max: ',max(sample_2['growthRate']))
#print('mean: ', np.mean(sample_2['growthRate']))

min:  -0.00916
max:  0.01873
mean:  0.004282928235294118

In [61]:
#
#print('min: ',min(sample_2['growthRate']))
#print('max: ',max(sample_2['growthRate']))
#print('mean: ', np.mean(sample_2['growthRate']))

min:  -0.00916
max:  0.01873
mean:  0.004282928235294118

In [63]:
#variable
#sample_2= np.where()
#median_ppsf >160
#QualityOfLifeTotalScore> 50
#density >?
#sold_above _list
sample_2['ppsf_category'] = np.where(sample_2['median_ppsf'] > np.mean(sample_2['median_ppsf']), 1, 0)

In [64]:
sample_2['quality_category'] = np.where(sample_2['QualityOfLifeTotalScore'] > np.mean(sample_2['QualityOfLifeTotalScore']), 1, 0)

In [66]:
sample_2['density_category'] = np.where(sample_2['density'] > np.mean(sample_2['density']), 1, 0)

In [67]:
sample_2['sold_above_category'] = np.where(sample_2['sold_above_list'] > np.mean(sample_2['sold_above_list']), 1, 0)

In [69]:
sample_2['education_category'] = np.where(sample_2['education_college_or_above'] > np.mean(sample_2['education_college_or_above']), 1, 0)

In [70]:
sample_2['income_category'] = np.where(sample_2['income_household_median'] > np.mean(sample_2['income_household_median']), 1, 0)

In [71]:
sample_2['growth_category'] = np.where(sample_2['growthRate'] > np.mean(sample_2['growthRate']), 1, 0)

In [73]:
sample_2['desirable']= np.where(sum(sample_2[['growth_category','income_category','education_category','sold_above_category','density_category','quality_category','ppsf_category']] > 3,1,0))

TypeError: sum() takes at most 2 arguments (3 given)

In [75]:
row_sums = sample_2[['ppsf_category','quality_category','density_category','sold_above_category','income_category','growth_category']].sum(axis=1)

# Set 'desirable' to 1 if the sum is greater than 3, otherwise 0
sample_2['desirable'] = np.where(row_sums > 3, 1, 0)

In [76]:
#shap values
sample_2['desirable'].value_counts()

0    72834
1    12166
Name: desirable, dtype: int64

In [3]:
### This is zillow data, expereimenting 
zillow_df = pd.read_csv("/Users/amelchristy/Downloads/Zillow-Scraper-results_5796_2023-12-22.csv")